apiVersion: v1
kind: Pod
metadata:
  name: sleeping-pod
  labels:
    app: sleeping-pod
spec:
  containers:
  - name: sleeping-container
    image: cuiyeshuai/blackhole
    resources:
      limits:
        memory: "500Mi"
        cpu: "0.5"
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - ubuntu-pod
        topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Service
metadata:
  name: sleeping-service
spec:
  selector:
    app: sleeping-pod
  ports:
  - protocol: TCP
    port: 80
  clusterIP: 10.96.0.100
  type: ClusterIP

---
apiVersion: v1
kind: Pod
metadata:
  name: netperf-client
  labels:
    app: netperf-client
    role: local
spec:
  containers:
  - image: sirot/netperf-latest
    command:
      - sleep
      - "7200"
    imagePullPolicy: IfNotPresent
    name: netperf
    resources:
      limits:
        memory: "4Gi"
        cpu: "2"
  restartPolicy: Always
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: role
            operator: In
            values:
            - local
        topologyKey: kubernetes.io/hostname
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: role
            operator: In
            values:
            - remote
          - key: app
            operator: In
            values:
            - sleeping-pod
        topologyKey: kubernetes.io/hostname
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netperf-deploy
  labels:
    app: netperf-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      role: remote
  template:
    metadata:
      labels:
        app: netperf-remote
        role: remote
    spec:
      containers:
      - name: netperf-remote
        image: sirot/netperf-latest
        command: ["/bin/sh","-c","netserver -p 4444 -4; iperf3 -s -i 1 -p 5201;"] 
        ports:
        - name: netperf-port
          containerPort: 4444
        - name: iperf-port
          containerPort: 5201
        resources:
          limits:
            memory: "8Gi"
            cpu: "4"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: role
                operator: In
                values:
                - local
              - key: app
                operator: In
                values:
                - sleeping-pod
            topologyKey: kubernetes.io/hostname
---
apiVersion: v1
kind: Service
metadata:
  name: netperf-remote-svc
spec:
  selector:
    role: remote
  type: NodePort
  ports:
  - name: netperf-port
    port: 4444
    targetPort: 4444
    nodePort: 31111
  - name: iperf-port
    port: 5201
    targetPort: 5201
    nodePort: 31112
  - name: netperf-data-port
    port: 4445
    targetPort: 4445
    nodePort: 31113
  clusterIP: 10.96.0.101
# k taint nodes kind-control-plane key=value:NoSchedule